spring.application.name=eureka-server

management.endpoints.web.exposure.include=*

server.port=8761

#eureka properties
eureka.client.service-url.defaultZone = http://localhost:8761/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
#it will be useful only in containers
eureka.instance.prefer-ip-address=true

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF